#!/usr/bin/env python3
"""Generate go/hash/poseidon_bls/consts.go from the vendored canonical hadeshash
reference (poseidonperm_x5_255_3.sage) — the Go twin of gen_consts_rs.py, so the
in-circuit hash and the risc0 poseidon_bls suite share identical constants."""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SAGE = os.path.join(HERE, "reference_x5_255_3.sage")
OUT  = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "consts.go")

src = open(SAGE).read()
prime = int(re.search(r"prime = (0x[0-9a-fA-F]+)", src).group(1), 16)
R_F = int(re.search(r"^R_F = (\d+)", src, re.M).group(1))
R_P = int(re.search(r"^R_P = (\d+)", src, re.M).group(1))
t   = int(re.search(r"^t = (\d+)", src, re.M).group(1))

BLS_FR = 0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001
assert prime == BLS_FR and (t, R_F, R_P) == (3, 8, 57)

rc  = [int(x, 16) for x in eval(re.search(r"round_constants = (\[[^\]]*\])", src).group(1))]
mds = [int(x, 16) for row in eval(re.search(r"MDS_matrix = (\[\[.*?\]\])", src, re.S).group(1)) for x in row]
assert len(rc) == (R_F + R_P) * t == 195 and len(mds) == t * t == 9

def arr(name, vals):
    lines = [f"var {name} = []string{{"]
    lines += [f'\t"{v}",' for v in vals]
    lines.append("}")
    return "\n".join(lines)

body = f'''// Code generated by stark-to-snark-bls/prototype/poseidon_bls/gen_consts_go.py. DO NOT EDIT.
//
// Canonical IAIK hadeshash parameters (poseidonperm_x5_255_3.sage @ pinned commit
// b5434fd2b2785926dd1dd386efbef167da57c064): Poseidon over BLS12-381 Fr, t=3, alpha=5, M=128.
// Identical to the constants baked into the risc0 `poseidon_bls` hash suite, so the in-circuit
// hash matches the seal hashing byte-for-byte.

package poseidon_bls

// Permutation parameters (original Poseidon, NOT Poseidon2).
const (
	Cells          = {t}  // state width
	RoundsHalfFull = {R_F // 2}  // full rounds on each side (R_F = {R_F})
	RoundsPartial  = {R_P}
	RoundsTotal    = 2*RoundsHalfFull + RoundsPartial
	SBoxExp        = 5 // x^5
)

{arr("roundConstantsDec", rc)}

{arr("mdsDec", mds)}
'''

open(OUT, "w").write(body)
print(f"wrote {OUT}: t={t}, R_F={R_F}, R_P={R_P}, #rc={len(rc)}, #mds={len(mds)}")
